<a href="https://colab.research.google.com/github/seungheee/algoStudy/blob/master/%EB%AF%B8%EB%8B%88_%EC%8B%A4%EC%8A%B51_CNN%EA%B3%BC_%EC%B9%9C%ED%95%B4%EC%A7%80%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1D CNN과 친해져요 :)

In [ ]:
import numpy as np
from tensorflow.keras.layers import Conv1D, MaxPool1D, GlobalMaxPooling1D

1. 길이가 10 토큰인 문장을 임베딩 사이즈=32로 임베딩한 것에 CNN 적용하기

In [ ]:
BATCH_SIZE = 1
SEQ_LEN = 10
EMBEDDING_SIZE = 32

embedded_input = np.array(np.random.normal(size=(BATCH_SIZE, SEQ_LEN, EMBEDDING_SIZE)), dtype=np.float32)
print(embedded_input.shape)

(1, 10, 32)


In [ ]:
KERNEL_SIZE1 = 3
NUM_FEATURE_MAP = 10

cnn_applied1 = Conv1D(filters = NUM_FEATURE_MAP, 
                     kernel_size = KERNEL_SIZE1, 
                     activation='relu')(embedded_input)

In [ ]:
print(cnn_applied1.shape)

(1, 8, 10)


In [ ]:
KERNEL_SIZE2 = 4
NUM_FEATURE_MAP = 10

cnn_applied2 = Conv1D(filters = NUM_FEATURE_MAP, 
                     kernel_size = KERNEL_SIZE2, 
                     activation='relu')(embedded_input)

In [ ]:
print(cnn_applied2.shape)

(1, 7, 10)


2. CNN feature map에 Max Pooling 적용하기

In [ ]:
POOL_SIZE1 = SEQ_LEN - KERNEL_SIZE1 + 1
## <- 이 계산을 알아서 해주는 것이 GlobalMaxPooling1D !!!
print("CNN applied size for kernel {} => {}".format(KERNEL_SIZE1, cnn_applied1.shape))
print("Pooling size for kernel {}     => {}".format(KERNEL_SIZE1, POOL_SIZE1))

max_pool_applied1 = GlobalMaxPooling1D()(cnn_applied1)
print(max_pool_applied1.shape)

CNN applied size for kernel 3 => (1, 8, 10)
Pooling size for kernel 3     => 8
(1, 10)


In [ ]:
embedded_input.shape

(1, 10, 32)

In [ ]:
cnn_applied1.shape

TensorShape([1, 8, 10])

In [ ]:
[a[1]for a in cnn_applied1[0]]

[<tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.8213649>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.4284496>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.30612946>]

In [ ]:
max_pool_applied1[0]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([1.6437994 , 1.8213649 , 2.257647  , 2.7558026 , 0.6202028 ,
       1.007894  , 1.5842854 , 2.4395413 , 0.53240544, 2.3295946 ],
      dtype=float32)>

In [ ]:
POOL_SIZE2 = SEQ_LEN - KERNEL_SIZE2 + 1
## <- 이 계산을 알아서 해주는 것이 GlobalMaxPooling1D !!!
print("CNN applied size for kernel {} => {}".format(KERNEL_SIZE2, cnn_applied2.shape))
print("Pooling size for kernel {}     => {}".format(KERNEL_SIZE2, POOL_SIZE2))

max_pool_applied2 = GlobalMaxPooling1D()(cnn_applied2)
print(max_pool_applied2.shape)

CNN applied size for kernel 4 => (1, 7, 10)
Pooling size for kernel 4     => 7
(1, 10)


3. 만들어진 feature들을 concat

In [15]:
concated_feature = tf.keras.layers.concatenate([max_pool_applied1, max_pool_applied2], axis=-1)
print(concated_feature.shape)

(1, 20)
